name: Styling

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  styling:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: olafurpg/setup-java@v10
        with:
          java-version: 11
