name: Unit-Test

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
        java: [ 8, 11 ]
    steps:
      - uses: actions/checkout@v2
      - uses: olafurpg/setup-scala@v10
        with:
          java-version: ${{ matrix.java }}
      - run: while sbt 'flow/testOnly *ExternalMinerMockSpec*'; do :; done
        shell: bash
